services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: gunicorn person_api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      SECRET_KEY: ${{ SECRET_KEY }}
      DEBUG: ${{ DEBUG }}
      DJANGO_ALLOWED_HOSTS: ${{ SECRET_KEY }}
      SQL_ENGINE: ${{ SQL_ENGINE }}
      SQL_DATABASE: ${{ SQL_DATABASE }}
      SQL_USER: ${{ SQL_USER }}
      SQL_PASSWORD: ${{ SQL_PASSWORD }}
      SQL_HOST: ${{ SQL_HOST }}
      SQL_PORT: ${{ SQL_PORT }}
      DATABASE: ${{ DATABASE }}
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${{ POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ POSTGRES_DB }}
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 5000:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:

