services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ali
      - POSTGRES_PASSWORD=aliali
      - POSTGRES_DB=personsdb

volumes:
  postgres_data: