name: Deploy Django Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          echo "DEBUG: $DEBUG"
          echo "SECRET_KEY is set to ${#SECRET_KEY} characters"  # Just print length for sensitive vars
          echo "DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS"
          echo "SQL_ENGINE: $SQL_ENGINE"
          echo "SQL_DATABASE: $SQL_DATABASE"
          echo "SQL_USER: $SQL_USER"
          echo "SQL_HOST: $SQL_HOST"
          echo "SQL_PORT: $SQL_PORT"
          echo "DATABASE: $DATABASE"
          echo "POSTGRES_USER: $POSTGRES_USER"
          echo "POSTGRES_DB: $POSTGRES_DB"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.SECRET_KEY }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PORT: ${{ secrets.SQL_PORT }}
          DATABASE: ${{ secrets.DATABASE }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        # run: |
        #   ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
        #     cd ${{ secrets.VPS_DEPLOY_PATH }}
        #     git pull origin main
        #     docker compose -f docker-compose.prod.yml down -v
        #     docker compose -f docker-compose.prod.yml up -d --build
        #   EOF